# Generated by Django 5.2.1 on 2025-08-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_address_same',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_parent_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.session'),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_address_same',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_class_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_parent_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/hsc-science/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_ssc_reg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_ssc_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='merit_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
