# Generated by Django 5.2.1 on 2025-08-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_degreeadmission_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreeadmission',
            name='add_father_bangla',
        ),
        migrations.RemoveField(
            model_name='degreeadmission',
            name='add_mother_bangla',
        ),
        migrations.RemoveField(
            model_name='hscadmissions',
            name='add_father_bangla',
        ),
        migrations.RemoveField(
            model_name='hscadmissions',
            name='add_mother_bangla',
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_father_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_father_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_hsc_institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_mother_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_mother_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_parent_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_ssc_institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='community',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='community_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='qouta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='qouta_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_father_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_father_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_mother_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_mother_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_parent_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_ssc_institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='community',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='community_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='qouta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='qouta_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_trxid',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_payment_method',
            field=models.CharField(blank=True, choices=[('rocket', 'Rocket')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_trxid',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
