# Generated by Django 5.2.1 on 2025-08-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_rename_add_upojella_degreeadmission_add_police_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
