# Generated by Django 5.2.1 on 2025-08-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_degreeadmission_add_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='sub_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
