# Generated by Django 5.2.1 on 2025-08-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_alter_hscadmissions_add_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='add_payment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], db_index=True, default='pending', max_length=10),
        ),
    ]
