# Generated by Django 5.2.1 on 2025-08-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('accountant', 'Accountant'), ('headteacher', 'Head Teacher'), ('teacher', 'Teacher'), ('assistant', 'Assistant'), ('sub_admin', 'Sub Admin'), ('admin', 'Admin'), ('master_admin', 'Master Admin')], default='student', max_length=20),
        ),
    ]
