# Generated by Django 5.2.1 on 2025-09-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cus_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
