# Generated by Django 5.2.1 on 2025-07-03 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Expense Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Income Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expense Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expense Amount')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Expense Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exp_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finances.expensecategory', verbose_name='Expense Category')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='income Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Income Amount')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Income Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finances.incomecategory', verbose_name='Income Category')),
            ],
        ),
    ]
