# Generated by Django 5.2.1 on 2025-07-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(verbose_name='Expense Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.IntegerField(verbose_name='Income Amount'),
        ),
    ]
