# Generated by Django 5.2.1 on 2025-07-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_studentinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
