# Generated by Django 5.2.1 on 2025-07-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvoice',
            name='add_payment_method',
            field=models.CharField(blank=True, choices=[('office', 'Office Cash'), ('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('others', 'Others')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='discount_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
