# Generated by Django 5.2.1 on 2025-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_studentinvoice_add_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='original_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
