# Generated by Django 5.2.1 on 2025-07-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_invoice_original_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='original_amount',
        ),
    ]
