# Generated by Django 5.2.1 on 2025-08-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=150)),
                ('group_name', models.CharField(blank=True, choices=[('science', 'Science'), ('humanities', 'Humanities'), ('business', 'Business Studies')], max_length=20, null=True)),
                ('exam_start_date', models.DateField()),
                ('exam_end_date', models.DateField()),
                ('exam_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.programs')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.session')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='exams.exam')),
                ('hsc_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='admissions.hscadmissions')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('group_name', models.CharField(blank=True, choices=[('all', 'All'), ('science', 'Science'), ('humanities', 'Humanities'), ('business', 'Business Studies')], default='all', max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=15, null=True)),
                ('program', models.ManyToManyField(blank=True, related_name='subjects_by_program', to='admissions.programs')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_marks', models.PositiveIntegerField(default=0)),
                ('pass_marks', models.PositiveIntegerField(default=0)),
                ('cq_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('cq_pass_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('mcq_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('mcq_pass_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('practical_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('practical_pass_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('ct_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('ct_pass_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(related_name='exam_subjects', through='exams.ExamSubject', to='exams.subject'),
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cq_mark', models.FloatField(blank=True, null=True)),
                ('mcq_mark', models.FloatField(blank=True, null=True)),
                ('practical_mark', models.FloatField(blank=True, null=True)),
                ('ct_mark', models.FloatField(blank=True, null=True)),
                ('total_mark', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.examrecord')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
            ],
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['exam'], name='exams_examr_exam_id_8ded35_idx'),
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['hsc_student'], name='exams_examr_hsc_stu_3a1aa6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examrecord',
            unique_together={('exam', 'hsc_student')},
        ),
        migrations.AddIndex(
            model_name='subjectmark',
            index=models.Index(fields=['exam_record'], name='exams_subje_exam_re_605e08_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectmark',
            index=models.Index(fields=['subject'], name='exams_subje_subject_7d4499_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectmark',
            unique_together={('exam_record', 'subject')},
        ),
    ]
