# Generated by Django 5.2.1 on 2025-07-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegreePrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deg_name', models.CharField(blank=True, max_length=20, null=True)),
                ('deg_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=15, null=True)),
                ('deg_year', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(blank=True, max_length=20, null=True)),
                ('pro_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=15, null=True)),
                ('pro_year', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ses_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(blank=True, max_length=30, null=True)),
                ('group', models.CharField(blank=True, choices=[('Science', 'Science'), ('Humanities', 'Humanities'), ('Business', 'Business')], max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_select', models.CharField(blank=True, choices=[('main', 'Main'), ('fourth', 'fourth'), ('all', 'all')], max_length=15, null=True)),
                ('sub_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscAdmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit_position', models.IntegerField()),
                ('add_name_bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('add_name', models.CharField(max_length=100)),
                ('add_mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('add_father_bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('add_father', models.CharField(blank=True, max_length=100, null=True)),
                ('add_father_mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('add_mother_bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('add_mother', models.CharField(blank=True, max_length=100, null=True)),
                ('add_mother_mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('add_parent', models.CharField(blank=True, max_length=100, null=True)),
                ('add_parent_mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('add_parent_relation', models.CharField(blank=True, max_length=20, null=True)),
                ('add_parent_service', models.CharField(blank=True, max_length=30, null=True)),
                ('add_parent_income', models.IntegerField(null=True)),
                ('add_parent_land_agri', models.CharField(blank=True, max_length=30, null=True)),
                ('add_parent_land_nonagri', models.CharField(blank=True, max_length=30, null=True)),
                ('add_village', models.CharField(blank=True, max_length=30, null=True)),
                ('add_post', models.CharField(blank=True, max_length=30, null=True)),
                ('add_upojella', models.CharField(blank=True, max_length=30, null=True)),
                ('add_distric', models.CharField(blank=True, max_length=30, null=True)),
                ('add_village_per', models.CharField(blank=True, max_length=30, null=True)),
                ('add_post_per', models.CharField(blank=True, max_length=30, null=True)),
                ('add_upojella_per', models.CharField(blank=True, max_length=30, null=True)),
                ('add_distric_per', models.CharField(blank=True, max_length=30, null=True)),
                ('add_birthdate', models.DateField(blank=True, null=True)),
                ('add_marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10, null=True)),
                ('add_ssc_roll', models.IntegerField(null=True)),
                ('add_ssc_reg', models.IntegerField(null=True)),
                ('add_ssc_session', models.CharField(blank=True, max_length=30, null=True)),
                ('add_ssc_gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('add_ssc_group', models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=10, null=True)),
                ('add_ssc_board', models.CharField(blank=True, max_length=10, null=True)),
                ('add_ssc_passyear', models.CharField(blank=True, max_length=10, null=True)),
                ('add_class_roll', models.IntegerField(null=True)),
                ('add_hsc_year', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd')], max_length=10, null=True)),
                ('add_blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('add_birth_certificate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('add_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('add_nationality', models.CharField(max_length=50)),
                ('add_religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=20)),
                ('add_photo', models.ImageField(upload_to='hsc-science/')),
                ('add_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.programs')),
                ('add_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.session')),
            ],
        ),
    ]
