# Generated by Django 5.2.1 on 2025-07-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='add_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_payment_method',
            field=models.CharField(blank=True, choices=[('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('others', 'Others')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_slip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_trxid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_hsc_year',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd')], default='1st', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_photo',
            field=models.ImageField(upload_to='admissions/hsc-science/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=20, null=True),
        ),
    ]
