# Generated by Django 5.2.1 on 2025-08-25 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_degreeadmission_add_address_same_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeadmission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_admissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='submitted_via',
            field=models.CharField(blank=True, choices=[('student_self', 'Student (self)'), ('staff', 'Staff (admin)'), ('import', 'Bulk import'), ('api', 'API')], default='student_self', max_length=20),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsc_admissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='submitted_via',
            field=models.CharField(blank=True, choices=[('student_self', 'Student (self)'), ('staff', 'Staff (admin)'), ('import', 'Bulk import'), ('api', 'API')], default='student_self', max_length=20),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
