# Generated by Django 5.2.1 on 2025-07-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_hscadmissions_add_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='add_address_same',
            field=models.BooleanField(default=False),
        ),
    ]
