# Generated by Django 5.2.1 on 2025-07-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_hscadmissions_add_address_same'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='admitted_students', to='admissions.subjects'),
        ),
    ]
