# Generated by Django 5.2.1 on 2025-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_remove_degreeadmission_add_father_bangla_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degreeadmission',
            old_name='add_upojella',
            new_name='add_police',
        ),
        migrations.RenameField(
            model_name='degreeadmission',
            old_name='add_upojella_per',
            new_name='add_police_per',
        ),
        migrations.RenameField(
            model_name='hscadmissions',
            old_name='add_upojella',
            new_name='add_police',
        ),
        migrations.RenameField(
            model_name='hscadmissions',
            old_name='add_upojella_per',
            new_name='add_police_per',
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_postal_per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='add_postal_per',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
