# Generated by Django 5.2.1 on 2025-07-07 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_hscadmissions_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='fourth_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_selected', to='admissions.subjects'),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='main_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_selected', to='admissions.subjects'),
        ),
    ]
