# Generated by Django 5.2.1 on 2025-07-07 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_hscadmissions_fourth_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.programs'),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_slip',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
