# Generated by Django 5.2.1 on 2025-08-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_hscadmissions_add_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_payment_method',
            field=models.CharField(blank=True, choices=[('rocket', 'Rocket')], default='rocket', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_payment_method',
            field=models.CharField(blank=True, choices=[('rocket', 'Rocket')], default='rocket', max_length=15, null=True),
        ),
    ]
