# Generated by Django 5.2.1 on 2025-07-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_hscadmissions_add_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hscadmissions',
            name='add_program',
        ),
    ]
