# Generated by Django 5.2.1 on 2025-07-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_remove_hscadmissions_add_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_category', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Fee Category Main')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_cat', to='admissions.feecategory', verbose_name='Fee Category')),
            ],
        ),
    ]
