# Generated by Django 5.2.1 on 2025-07-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_feecategory_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fee',
            name='fee_category',
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_program', to='admissions.programs', verbose_name='Fee Program'),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_session', to='admissions.session', verbose_name='Fee Session'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_group', to='admissions.group', verbose_name='Fee Group'),
        ),
        migrations.DeleteModel(
            name='FeeCategory',
        ),
    ]
