# Generated by Django 5.2.1 on 2025-08-27 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_alter_subjects_sub_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_mobile',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='hscadmissions',
            constraint=models.UniqueConstraint(fields=('add_admission_group', 'add_class_roll'), name='unique_roll_per_group'),
        ),
    ]
