# Generated by Django 5.2.1 on 2025-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_group_remove_fee_fee_category_fee_fee_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce')], max_length=20, null=True),
        ),
    ]
