# Generated by Django 5.2.1 on 2025-08-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_hscadmissions_add_payment_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_ssc_passyear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
