# Generated by Django 5.2.1 on 2025-07-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_alter_group_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='fee_name',
        ),
    ]
