# Generated by Django 5.2.1 on 2025-07-07 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_remove_fee_fee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='add_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.programs'),
        ),
    ]
