# Generated by Django 5.2.1 on 2025-08-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_alter_hscadmissions_add_ssc_passyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_birth_certificate_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_slip',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
