# Generated by Django 5.2.1 on 2025-07-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_hscadmissions_add_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='sub_select',
        ),
    ]
