# Generated by Django 5.2.1 on 2025-08-31 14:30

import apps.admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_alter_hscadmissions_add_birth_certificate_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/hsc-science/%Y/%m/%d/', validators=[apps.admissions.models.validate_photo_500kb]),
        ),
    ]
