# Generated by Django 5.2.1 on 2025-07-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_remove_subjects_sub_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='sub_select',
            field=models.CharField(blank=True, choices=[('main', 'Main'), ('fourth', 'Fourth'), ('optional', 'Optional'), ('all', 'All')], max_length=15, null=True),
        ),
    ]
