# Generated by Django 5.2.1 on 2025-09-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_alter_hscadmissions_add_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_birth_certificate_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
