# Generated by Django 5.2.1 on 2025-07-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_subjects_sub_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='add_parent_select',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
