# Generated by Django 5.2.1 on 2025-09-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_alter_hscadmissions_add_birth_certificate_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='add_class_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
