# Generated by Django 5.2.1 on 2025-07-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_hscadmissions_add_parent_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='add_admission_group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.session'),
        ),
    ]
