# Generated by Django 5.2.1 on 2025-09-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_hscadmissions_add_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_ssc_group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Humanities'), ('commerce', 'Business Studies'), ('technical', 'Technical')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_ssc_reg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
