# Generated by Django 5.2.1 on 2025-07-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_hscadmissions_add_admission_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='sub_select',
            field=models.CharField(blank=True, choices=[('main', 'Main'), ('fourth', 'Fourth'), ('optional', 'Optional'), ('optional2', 'Optional2'), ('all', 'All')], max_length=15, null=True),
        ),
    ]
