# Generated by Django 5.2.1 on 2025-09-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_alter_hscadmissions_add_ssc_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeadmission',
            name='add_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_father_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_grand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_mother_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
