# Generated by Django 5.2.1 on 2025-07-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_alter_subjects_sub_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissions',
            name='optional_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_selected_1', to='admissions.subjects'),
        ),
        migrations.AddField(
            model_name='hscadmissions',
            name='optional_subject_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_selected_2', to='admissions.subjects'),
        ),
    ]
