# Generated by Django 5.2.1 on 2025-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_degreeadmission_add_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_slip',
            field=models.CharField(blank=True, null=True),
        ),
    ]
