# Generated by Django 5.2.1 on 2025-07-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0018_hscadmissions_optional_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_ssc_board',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Cumilla', 'Cumilla'), ('Rajshahi', 'Rajshahi'), ('Jashore', 'Jashore'), ('Sylhet', 'Sylhet'), ('Barishal', 'Barishal'), ('Dinajpur', 'Dinajpur'), ('Mymensingh', 'Mymensingh'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical')], max_length=10, null=True),
        ),
    ]
