# Generated by Django 5.2.1 on 2025-09-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0018_alter_degreeadmission_add_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeadmission',
            name='add_class_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='op1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_op1', to='admissions.degreesubjects'),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='op2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_op2', to='admissions.degreesubjects'),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='op3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_op3', to='admissions.degreesubjects'),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='op4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_op4', to='admissions.degreesubjects'),
        ),
    ]
