# Generated by Django 5.2.1 on 2025-09-16 10:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_degreeadmission_add_class_id_degreeadmission_op1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreesubjects',
            name='sub_select',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('main', 'Main'), ('op1', 'op1'), ('op2', 'op2'), ('op3', 'op3'), ('op4', 'op4'), ('all', 'All')], max_length=100, null=True),
        ),
    ]
