# Generated by Django 5.2.1 on 2025-07-10 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_alter_hscadmissions_add_ssc_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ses_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(blank=True, max_length=30, null=True)),
                ('group', models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_name', models.CharField(max_length=100)),
                ('add_name_bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('add_mobile', models.CharField(max_length=15)),
                ('add_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('add_birthdate', models.DateField(blank=True, null=True)),
                ('add_ssc_roll', models.CharField(blank=True, max_length=20, null=True)),
                ('add_ssc_reg', models.CharField(blank=True, max_length=20, null=True)),
                ('add_ssc_session', models.CharField(blank=True, max_length=30, null=True)),
                ('add_ssc_gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('add_ssc_board', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Cumilla', 'Cumilla'), ('Rajshahi', 'Rajshahi'), ('Jashore', 'Jashore'), ('Sylhet', 'Sylhet'), ('Barishal', 'Barishal'), ('Dinajpur', 'Dinajpur'), ('Mymensingh', 'Mymensingh'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical')], max_length=10, null=True)),
                ('add_ssc_group', models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=10, null=True)),
                ('add_ssc_passyear', models.CharField(blank=True, max_length=10, null=True)),
                ('add_hsc_roll', models.CharField(blank=True, max_length=20, null=True)),
                ('add_hsc_reg', models.CharField(blank=True, max_length=20, null=True)),
                ('add_hsc_session', models.CharField(blank=True, max_length=30, null=True)),
                ('add_hsc_gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('add_hsc_board', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Cumilla', 'Cumilla'), ('Rajshahi', 'Rajshahi'), ('Jashore', 'Jashore'), ('Sylhet', 'Sylhet'), ('Barishal', 'Barishal'), ('Dinajpur', 'Dinajpur'), ('Mymensingh', 'Mymensingh'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical')], max_length=10, null=True)),
                ('add_hsc_group', models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=10, null=True)),
                ('add_hsc_passyear', models.CharField(blank=True, max_length=10, null=True)),
                ('add_admission_group', models.CharField(blank=True, choices=[('Ba', 'Ba'), ('Bss', 'Bss'), ('Bbs', 'Bbs'), ('Bsc', 'Bsc')], max_length=20, null=True)),
                ('add_father', models.CharField(blank=True, max_length=100, null=True)),
                ('add_mother', models.CharField(blank=True, max_length=100, null=True)),
                ('add_class_roll', models.CharField(blank=True, max_length=20, null=True)),
                ('merit_position', models.CharField(blank=True, max_length=10, null=True)),
                ('add_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('add_payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('add_trxid', models.CharField(blank=True, max_length=50, null=True)),
                ('add_slip', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.degreeprograms')),
                ('add_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.degreesession')),
                ('main_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_main_subject', to='admissions.degreesubjects')),
                ('subjects', models.ManyToManyField(blank=True, to='admissions.degreesubjects')),
            ],
        ),
    ]
