# Generated by Django 5.2.1 on 2025-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_degreesubjects_sub_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreesubjects',
            name='group',
            field=models.CharField(blank=True, choices=[('All', 'ALL'), ('Ba', 'BA'), ('Bss', 'BSS'), ('Bbs', 'BBS'), ('Bsc', 'BSC')], max_length=20, null=True),
        ),
    ]
