# Generated by Django 5.2.1 on 2025-07-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_degreesession_degreesubjects_degreeadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreesubjects',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='degreesubjects',
            name='group',
            field=models.CharField(blank=True, choices=[('Ba', 'Ba'), ('Bss', 'Bss'), ('Bbs', 'Bbs'), ('Bsc', 'Bsc')], max_length=20, null=True),
        ),
    ]
