# Generated by Django 5.2.1 on 2025-07-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_degreesubjects_sub_status_alter_degreesubjects_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeadmission',
            name='add_address_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_birth_certificate_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_distric',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_distric_per',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_father_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_father_mobile',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_mother_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_mother_mobile',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_parent_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_parent_land_agri',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_parent_land_nonagri',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_parent_mobile',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_parent_relation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_parent_select',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_parent_service',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_post',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_post_per',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_upojella',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_upojella_per',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_village',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_village_per',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_photo',
            field=models.ImageField(blank=True, null=True, upload_to='degree/student_photos/'),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
    ]
