# Generated by Django 5.2.1 on 2025-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_alter_degreesubjects_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreesubjects',
            name='sub_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
