# Generated by Django 5.2.1 on 2025-09-16 10:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0022_alter_degreesubjects_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreesubjects',
            name='group',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('All', 'ALL'), ('Ba', 'BA'), ('Bss', 'BSS'), ('Bbs', 'BBS'), ('Bsc', 'BSC')], max_length=100, null=True),
        ),
    ]
