# Generated by Django 5.2.1 on 2025-07-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0022_degreeadmission_add_address_same_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Ba', 'Ba'), ('Bss', 'Bss'), ('Bbs', 'Bbs'), ('Bsc', 'Bsc')], max_length=20, null=True),
        ),
    ]
