# Generated by Django 5.2.1 on 2025-07-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_alter_group_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.session'),
        ),
    ]
