# Generated by Django 5.2.1 on 2025-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0024_alter_degreeadmission_add_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_father_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_mother_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_parent_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
