# Generated by Django 5.2.1 on 2025-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0024_degreeadmission_add_admission_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeadmission',
            name='add_payment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='add_payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], db_index=True, default='pending', max_length=10),
        ),
    ]
