# Generated by Django 5.2.1 on 2025-07-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0025_alter_hscadmissions_add_father_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_father_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_hsc_group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Humanities'), ('commerce', 'Business Studies')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_mother_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_parent_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_ssc_group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Humanities'), ('commerce', 'Business Studies')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Humanities'), ('commerce', 'Business Studies'), ('Ba', 'Ba'), ('Bss', 'Bss'), ('Bbs', 'Bbs'), ('Bsc', 'Bsc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_admission_group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Humanities'), ('commerce', 'Business Studies')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_payment_method',
            field=models.CharField(blank=True, choices=[('office', 'Office Cash'), ('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('others', 'Others')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hscadmissions',
            name='add_ssc_group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Humanities'), ('commerce', 'Business Studies')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Humanities'), ('commerce', 'Business Studies')], max_length=20, null=True),
        ),
    ]
