# Generated by Django 5.2.1 on 2025-07-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0026_alter_degreeadmission_add_father_mobile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together={('fee_session', 'fee_program', 'fee_group')},
        ),
    ]
