# Generated by Django 5.2.1 on 2025-07-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0027_alter_fee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeadmission',
            name='add_payment_method',
            field=models.CharField(blank=True, choices=[('office', 'Office Cash'), ('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('others', 'Others')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Humanities'), ('commerce', 'Business Studies'), ('Ba', 'BA'), ('Bss', 'BSS'), ('Bbs', 'BBS'), ('Bsc', 'BSC')], max_length=20, null=True),
        ),
    ]
