# Generated by Django 5.2.1 on 2025-08-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Expense Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Income Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expense Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.IntegerField(verbose_name='Expense Amount')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Expense Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exp_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finances.expensecategory', verbose_name='Expense Category')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='income Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.IntegerField(verbose_name='Income Amount')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Income Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finances.incomecategory', verbose_name='Income Category')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('invoice_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_group', to='admissions.group', verbose_name='invoice Group')),
                ('invoice_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_program', to='admissions.programs', verbose_name='invoice Program')),
                ('invoice_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_session', to='admissions.session', verbose_name='invoice Session')),
                ('invoice_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_purpose', to='finances.purpose', verbose_name='invoice Purpose')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('add_payment_method', models.CharField(blank=True, choices=[('office', 'Office Cash'), ('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('others', 'Others')], max_length=15, null=True)),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_invoices', to='finances.invoice')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'invoice')},
            },
        ),
    ]
